# In example:
# 3 stone
# armor is just the diamond set.
# cooldown 50 seconds

kits:
  example:
    items:
    - 1:3
    helmet: 310
    chestplate: 311
    leggings: 312
    boots: 313
    cooldown: 50